name: Build and Push Job Images to ECR

on:
  push:
    branches:
      - beatly

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push job1_preprocessor image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO_NAME:job1_preprocessor-latest jobs/job1_preprocessor
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO_NAME:job1_preprocessor-latest

      - name: Build, tag, and push job2_rpeak image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO_NAME:job2_rpeak-latest jobs/job2_rpeak
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO_NAME:job2_rpeak-latest

      - name: Build, tag, and push job3_beats image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO_NAME:job3_beats-latest jobs/job3_beats
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO_NAME:job3_beats-latest

      - name: Build, tag, and push job4_pqst image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO_NAME:job4_pqst-latest jobs/job4_pqst
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO_NAME:job4_pqst-latest

      - name: Build, tag, and push job5_a1_integ image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO_NAME:job5_a1_integ-latest jobs/job5_a1_integ
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO_NAME:job5_a1_integ-latest

      - name: Build, tag, and push job6_templates image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO_NAME:job6_templates-latest jobs/job6_templates
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO_NAME:job6_templates-latest 