name: Build and Push Job Images to ECR

# on:
#   push:
#     branches:
      # - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push job1 image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO_NAME:job1-latest jobs/job1
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO_NAME:job1-latest

      - name: Build, tag, and push job2 image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO_NAME:job2-latest jobs/job2
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO_NAME:job2-latest

      - name: Build, tag, and push job3 image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO_NAME:job3-latest jobs/job3
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO_NAME:job3-latest
